version: "3.3"
services:
  mongo:
    image: mongo:4.4
    command: --nojournal
  orion:
    image: marcdespland/orion-ld:FIWARE_8.0_arm64
    environment:
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=orion
      - ORIONLD_TROE_HOST=timescale
      - ORIONLD_MONGO_HOST=mongo
    depends_on:
      - mongo
      - timescale
    command: -dbhost mongo -logLevel DEBUG  -forwarding
  timescale:
    image: marcdespland/timescaledb-postgis:latest-pg12
    hostname: timescale
    container_name: timescale
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orion"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 60s
    environment:
      - POSTGRES_USER=orion
      - POSTGRES_PASSWORD=orion
      - POSTGRES_HOST_AUTH_METHOD=trust
  mintaka:
    image: marcdespland/mintaka:latest
    hostname: mintaka
    container_name: mintaka
    environment:
      - DATASOURCES_DEFAULT_HOST=timescale
      - DATASOURCES_DEFAULT_USERNAME=orion
      - DATASOURCES_DEFAULT_PASSWORD=orion
      - DATASOURCES_DEFAULT_DATABSE=orion
    depends_on:
      - orion
      - timescale
  test:
    image: marcdespland/test-ngsi-ld:1.0.0
    environment:
      - ORION_API=http://proxyld:8080
      - DEFAULT_SERVICE=default
      - DEFAULT_SERVICEPATH=/
    depends_on:
      - proxyld
  proxyld:
    restart: always
    build: ./proxyld
    image: proxyld:latest
    container_name: proxyld
    hostname: proxyld
    depends_on:
      - orion
      - mintaka